import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>LeetClone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>Hellow world</h1>
      </main>
    </>
  );
}
